# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mUtKemCk3qX_9qWcbIkf_sOjOlRBaPb4
"""

import pandas as pd

# Load the spreadsheet into Python
df = pd.read_csv('employee_data.csv')

# Look at the first 5 rows to see what we are dealing with
df.head()

# 1. Check how many rows we have right now
initial_rows = len(df)
print(f"Starting row count: {initial_rows}")

# 2. Drop rows that are exact duplicates
df = df.drop_duplicates()

# 3. Check how many rows are left
after_dedup_rows = len(df)
print(f"Row count after removing duplicates: {after_dedup_rows}")
print(f"We removed {initial_rows - after_dedup_rows} duplicate rows!")

# Check if any Employee ID is repeated
id_duplicates = df.duplicated(subset=['EmpID']).sum()

print(f"Number of rows with repeating Employee IDs: {id_duplicates}")

# Count how many missing (null) values exist in every single column
print("--- Missing Values Per Column ---")
print(df.isnull().sum())

# Cross-tabulate Employee Status against missing Exit Dates
# True means the value IS missing (Null). False means a date is there.
print("--- Checking Missing Exit Dates by Employee Status ---")
print(pd.crosstab(df['EmployeeStatus'], df['ExitDate'].isnull()))

# Look at all unique categories in EmployeeStatus and GenderCode to check for messy text
print("--- Unique Values in EmployeeStatus ---")
print(df['EmployeeStatus'].unique())

print("\n--- Unique Values in GenderCode ---")
print(df['GenderCode'].unique())

# Create a filter for Active employees who have an Exit Date
corruption_filter = (df['EmployeeStatus'] == 'Active') & (df['ExitDate'].notnull())

# Isolate these rows into a separate look
corrupted_employees = df[corruption_filter]

# Let's look at the first 5 rows of this corrupted group, specifically their names, status, and dates
print(f"Total corrupted records found: {len(corrupted_employees)}")
corrupted_employees[['FirstName', 'LastName', 'EmployeeStatus', 'StartDate', 'ExitDate']].head()

# Check what data type Python is using for our dates
print(df[['StartDate', 'ExitDate']].dtypes)

# Convert our date columns from text (object) to true Datetime format
df['StartDate'] = pd.to_datetime(df['StartDate'], errors='coerce')
df['ExitDate'] = pd.to_datetime(df['ExitDate'], errors='coerce')

# Let's verify the change worked
print("--- New Data Types ---")
print(df[['StartDate', 'ExitDate']].dtypes)

# Filter out our 991 mysterious active employees who have an exit date
active_with_exit = df[(df['EmployeeStatus'] == 'Active') & (df['ExitDate'].notnull())]

# Calculate how many of them have an Exit Date that happens BEFORE their Start Date
backwards_dates = (active_with_exit['ExitDate'] < active_with_exit['StartDate']).sum()

print(f"Out of 991 mystery records:")
print(f"Number of employees where ExitDate is BEFORE StartDate: {backwards_dates}")

# Filter the 991 active employees with exit dates again
active_with_exit = df[(df['EmployeeStatus'] == 'Active') & (df['ExitDate'].notnull())]

# Find the earliest and latest exit dates in this group
earliest_exit = active_with_exit['ExitDate'].min()
latest_exit = active_with_exit['ExitDate'].max()

print(f"For the 991 Active employees with an Exit Date:")
print(f"The earliest exit date recorded is: {earliest_exit}")
print(f"The latest exit date recorded is: {latest_exit}")

# 1. Find the rows where status is Active but they have an Exit Date
glitch_filter = (df['EmployeeStatus'] == 'Active') & (df['ExitDate'].notnull())

# 2. Programmatically change their status from 'Active' to 'Terminated'
df.loc[glitch_filter, 'EmployeeStatus'] = 'Terminated'

# 3. Let's run our cross-tabulation audit again to verify the fix worked!
print("--- Post-Correction Audit Matrix ---")
print(pd.crosstab(df['EmployeeStatus'], df['ExitDate'].isnull()))

# Replace missing values in TerminationDescription with standard placeholder text
df['TerminationDescription'] = df['TerminationDescription'].fillna('N/A - Active Employee')

# Verify that there are absolutely zero null values left in the entire dataset!
print("--- Check for any remaining Nulls ---")
print(df.isnull().sum())

# Save your cleaned dataframe to a new CSV file
df.to_csv('clean_master_workforce_data.csv', index=False)
print("🎉 Success! Your clean dataset has been created.")